services:
  www:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb:latest
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55