services:
  www:
    container_name: contenedor-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    networks:
      - red-interna

  db:
    container_name: contenedor-bd
    image: mariadb:11.7.2
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - red-interna

  phpmyadmin:
    container_name: contenedor-phpmyadmin
    image: phpmyadmin:5.2.1-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db               
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge
